CREATE SCHEMA IF NOT EXISTS SILO;

SET SCHEMA SILO;

DROP TABLE IF EXISTS RESIDENT;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DEPARTMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE RESIDENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    JOB_FUNCTION VARCHAR(100) NOT NULL,
    SILO_LEVEL INT NOT NULL,
    DEPARTMENT_ID INT NOT NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES SILO.DEPARTMENT(ID)
);